name: Semantic Release

on: workflow_dispatch

jobs:
  release:
    name: Semantic Release
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Install dependencies
      run: |
        npm install
    - name: Compiling
      run: |
        npm run compile
    - name: Release
      env:
        GITHUB_TOKEN: ${{ secrets.SEMANTIC_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: npx semantic-release